"""Add last_updated column

Revision ID: 6b6ce0180822
Revises: 
Create Date: 2025-04-02 19:57:49.471533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b6ce0180822'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_updated', sa.DateTime(), nullable=True))

    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_updated', sa.DateTime(), nullable=True))

    with op.batch_alter_table('schedule_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_updated', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule_entry', schema=None) as batch_op:
        batch_op.drop_column('last_updated')

    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.drop_column('last_updated')

    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.drop_column('last_updated')

    # ### end Alembic commands ###
